<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from lalg-civi-sync/xml/schema/CRM/LalgCiviSync/LalgCmsUser.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:cbc814062c87efee02db17d5b0b8ceb7)
 */
use CRM_LalgCiviSync_ExtensionUtil as E;

/**
 * Database access object for the LalgCmsUser entity.
 */
class CRM_LalgCiviSync_DAO_LalgCmsUser extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'lalg_cms_user';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique LalgCmsUser ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * FK to Contact
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $contact_id;

  /**
   * Id of Drupal User
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $user_id;

  /**
   * Login username
   *
   * @var string|null
   *   (SQL type: varchar(60))
   *   Note that values will be retrieved from the database as a string.
   */
  public $username;

  /**
   * Email Address
   *
   * @var string|null
   *   (SQL type: varchar(254))
   *   Note that values will be retrieved from the database as a string.
   */
  public $email;

  /**
   * Last User Login
   *
   * @var string|null
   *   (SQL type: timestamp)
   *   Note that values will be retrieved from the database as a string.
   */
  public $last_login;

  /**
   * Last User Access
   *
   * @var string|null
   *   (SQL type: timestamp)
   *   Note that values will be retrieved from the database as a string.
   */
  public $last_access;

  /**
   * Id of Drupal Group
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $group_id;

  /**
   * Drupal Group Name
   *
   * @var string|null
   *   (SQL type: varchar(254))
   *   Note that values will be retrieved from the database as a string.
   */
  public $group_name;

  /**
   * Drupal Group Role
   *
   * @var string|null
   *   (SQL type: varchar(60))
   *   Note that values will be retrieved from the database as a string.
   */
  public $group_role;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'lalg_cms_user';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Lalg Cms Users') : E::ts('Lalg Cms User');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'contact_id', 'civicrm_contact', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique LalgCmsUser ID'),
          'required' => TRUE,
          'where' => 'lalg_cms_user.id',
          'table_name' => 'lalg_cms_user',
          'entity' => 'LalgCmsUser',
          'bao' => 'CRM_LalgCiviSync_DAO_LalgCmsUser',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'contact_id' => [
          'name' => 'contact_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Contact ID'),
          'description' => E::ts('FK to Contact'),
          'where' => 'lalg_cms_user.contact_id',
          'table_name' => 'lalg_cms_user',
          'entity' => 'LalgCmsUser',
          'bao' => 'CRM_LalgCiviSync_DAO_LalgCmsUser',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
          'add' => NULL,
        ],
        'user_id' => [
          'name' => 'user_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('User ID'),
          'description' => E::ts('Id of Drupal User'),
          'where' => 'lalg_cms_user.user_id',
          'table_name' => 'lalg_cms_user',
          'entity' => 'LalgCmsUser',
          'bao' => 'CRM_LalgCiviSync_DAO_LalgCmsUser',
          'localizable' => 0,
          'add' => NULL,
        ],
        'username' => [
          'name' => 'username',
          'type' => CRM_Utils_Type::T_VARCHAR(60),
          'title' => E::ts('Username'),
          'description' => E::ts('Login username'),
          'where' => 'lalg_cms_user.username',
          'table_name' => 'lalg_cms_user',
          'entity' => 'LalgCmsUser',
          'bao' => 'CRM_LalgCiviSync_DAO_LalgCmsUser',
          'localizable' => 0,
          'add' => NULL,
        ],
        'email' => [
          'name' => 'email',
          'type' => CRM_Utils_Type::T_VARCHAR(254),
          'title' => E::ts('Email'),
          'description' => E::ts('Email Address'),
          'where' => 'lalg_cms_user.email',
          'table_name' => 'lalg_cms_user',
          'entity' => 'LalgCmsUser',
          'bao' => 'CRM_LalgCiviSync_DAO_LalgCmsUser',
          'localizable' => 0,
          'add' => NULL,
        ],
        'last_login' => [
          'name' => 'last_login',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => E::ts('Last Login'),
          'description' => E::ts('Last User Login'),
          'where' => 'lalg_cms_user.last_login',
          'table_name' => 'lalg_cms_user',
          'entity' => 'LalgCmsUser',
          'bao' => 'CRM_LalgCiviSync_DAO_LalgCmsUser',
          'localizable' => 0,
          'add' => NULL,
        ],
        'last_access' => [
          'name' => 'last_access',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => E::ts('Last Access'),
          'description' => E::ts('Last User Access'),
          'where' => 'lalg_cms_user.last_access',
          'table_name' => 'lalg_cms_user',
          'entity' => 'LalgCmsUser',
          'bao' => 'CRM_LalgCiviSync_DAO_LalgCmsUser',
          'localizable' => 0,
          'add' => NULL,
        ],
        'group_id' => [
          'name' => 'group_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Group ID'),
          'description' => E::ts('Id of Drupal Group'),
          'where' => 'lalg_cms_user.group_id',
          'table_name' => 'lalg_cms_user',
          'entity' => 'LalgCmsUser',
          'bao' => 'CRM_LalgCiviSync_DAO_LalgCmsUser',
          'localizable' => 0,
          'add' => NULL,
        ],
        'group_name' => [
          'name' => 'group_name',
          'type' => CRM_Utils_Type::T_VARCHAR(254),
          'title' => E::ts('Group Name'),
          'description' => E::ts('Drupal Group Name'),
          'where' => 'lalg_cms_user.group_name',
          'table_name' => 'lalg_cms_user',
          'entity' => 'LalgCmsUser',
          'bao' => 'CRM_LalgCiviSync_DAO_LalgCmsUser',
          'localizable' => 0,
          'add' => NULL,
        ],
        'group_role' => [
          'name' => 'group_role',
          'type' => CRM_Utils_Type::T_VARCHAR(254),
          'title' => E::ts('Group Role'),
          'description' => E::ts('Drupal Group Role'),
          'where' => 'lalg_cms_user.group_role',
          'table_name' => 'lalg_cms_user',
          'entity' => 'LalgCmsUser',
          'bao' => 'CRM_LalgCiviSync_DAO_LalgCmsUser',
          'localizable' => 0,
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, '_user', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, '_user', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
